INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '031', 'assigné à résidence SE','ARSE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '001', 'condamné détenu','CD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '017', 'contraint par corps','CPC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '002', 'contraint-dettier','CT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '029', 'contrainte judiciaire','CJUD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '027', 'détenu décédé','DCD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '025', 'détenu en fuite','FUIT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '024', 'détenu libérable sous réserve du versement d''un cautionnement','DLC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '009', 'détenu pour autre cause','DPAC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '030', 'détenu provisoirement','DP') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '007', 'détenu prévenu','PR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '008', 'détenu prévenu pour cette cause','DET') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '015', 'détenu sous le régime de la semi-liberté','DSL') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '33', 'détenu à domicile sous SE','DDSE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '004', 'détenu évadé','EVD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '013', 'incarcéré provisoire','INCP') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '028', 'inconnue','IN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '005', 'libre','LIB') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '018', 'maintenu en détention sous le régime douanier','MDDOUAN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '32', 'placé sous MDDIFF','MDDIFF') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '010', 'placé sous contrôle judiciaire','CJ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '012', 'placé sous le régime de la liberté surveillée','LS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '021', 'placé sous surveillance électronique','PSE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '014', 'prévenu détenu pour cette cause','PD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '019', 'retenu administrativement','RETADM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '020', 'retenu sous escorte','ESCORTE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '016', 'sous l''effet de la prise de corps','PCORPS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.categorie_penale(id, code, libelle, mnemo)VALUES(nextval('webapp.categorie_penale_id_seq'), '34', 'écrou extraditionnel','EEXTR') ON CONFLICT DO NOTHING;