INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '41', 'a la garde de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '25', 'ami','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '26', 'amie','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '27', 'beau frère','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '37', 'beau père','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '9', 'beau-fils','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '10', 'belle fille','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '58', 'belle mère','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '28', 'belle soeur','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '52', 'cousin','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '53', 'cousine','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '7', 'demi frère','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '8', 'demi soeur','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '34', 'divorcé de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '49', 'famille d''accueil','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '4', 'fille adoptive de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '2', 'fille de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '23', 'filleul','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '24', 'filleule','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '3', 'fils adoptif de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '1', 'fils de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '5', 'frère','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '39', 'gardiens de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '40', 'gardiens de fait de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '38', 'gardé de fait','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '60', 'grand mère maternelle','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '61', 'grand mère paternelle','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '43', 'grand père maternel de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '44', 'grand père paternel de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '56', 'marraine','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '33', 'mère','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '51', 'mère adoptive de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '21', 'neveu','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '22', 'nièce','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '36', 'oncle','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '35', 'parrain','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '59', 'personne digne de confiance','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '13', 'petit fils (lien grand père maternel)','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '11', 'petit fils (lien grand père paternel)','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '14', 'petit fils (lien grand-mère maternelle)','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '12', 'petit fils (lien grand-mère paternelle)','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '17', 'petite fille (lien grand père maternel)','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '15', 'petite fille (lien grand père paternel)','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '18', 'petite fille (lien grand-mère maternelle)','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '16', 'petite fille (lien grand-mère paternelle)','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '20', 'placé sous la garde de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '32', 'père','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '50', 'père adoptif de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '6', 'soeur','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '57', 'tante','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '54', 'veuf de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '55', 'veuve de','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '31', 'vit avec','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '30', 'épouse','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '29', 'époux','') ON CONFLICT DO NOTHING;
INSERT INTO webapp.lien_social(id, code, libelle, mnemo)VALUES(nextval('webapp.lien_social_id_seq'), '0', '','') ON CONFLICT DO NOTHING;
