INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'AVERTIS', 'avertissement','AVERTIS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'ACONTRA', 'avis de contravention -ACO-','ACONTRA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'CD', 'citation directe','CD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'CPP', 'citation par partie poursuivante','CPP') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'CLASSMT', 'classement','CLASSMT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'CONVGRE', 'Convocation par greffier','CONVGRE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'CVCEP', 'convocation par le chef d''établissement pénitentiaire','CVCEP') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'COPJ', 'convocation par OPJ','COPJ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'CPV', 'convocation par procès verbal du PR','CPV') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'CPVMIN', 'convocation par procès-verbal (mineurs)','CPVMIN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'COPJMEX', 'COPJ aux fins de mise en examen','COPJMEX') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'DESSAIS', 'dessaisissement','DESSAIS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'DESCIV', 'dessaisissement en matière civile','DESCIV') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'EXCOMPO', 'exécution de la composition pénale hors validation','EXCOMPO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'JONCT', 'jonction','JONCT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'PROALT', 'procédure alternative aux poursuites','PROALT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'COMPO', 'procès verbal de proposition de composition pénale','COMPO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'PV-CDD', 'procès-verbal de comparution à délai différé','PV-CDD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'PV-CI', 'procès-verbal de comparution immédiate','PV-CI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'PV-CP', 'procès-verbal de comparution préalable','PV-CP') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'PVCRPC', 'procès-verbal de proposition de peine sur RPC','PVCRPC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'PV-CITA', 'procès-verbal valant citation à parquet','PV-CITA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'COMPO2', 'PV de proposition de composition pénale après délai de réflexion','COMPO2') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'ROP', 'réquisitions d''ordonnance pénale','ROP') ON CONFLICT DO NOTHING;
INSERT INTO webapp.mode_poursuite(id, code, libelle, mnemo)VALUES(nextval('webapp.mode_poursuite_id_seq'), 'RI', 'réquisitoire introductif','RI') ON CONFLICT DO NOTHING;