INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '060', 'BERMUDES','BM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '004', 'AFGHANISTAN','AF') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '710', 'AFRIQUE DU SUD','ZA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '008', 'ALBANIE','AL') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '012', 'ALGERIE','DZ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '276', 'ALLEMAGNE','DE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '020', 'ANDORRE','AD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '024', 'ANGOLA','AO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '660', 'ANGUILLA','AI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '010', 'ANTARCTIQUE','AQ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '028', 'ANTIGUA-ET-BARBUDA','AG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '532', 'ANTILLES NEERLANDAISES','AN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '682', 'ARABIE SAOUDITE','SA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '032', 'ARGENTINE','AR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '051', 'ARMENIE','AM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '533', 'ARUBA','AW') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '036', 'AUSTRALIE','AU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '997', 'AUTRES PAYS','XB') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '040', 'AUTRICHE','AT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '031', 'AZERBAIDJAN','AZ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '044', 'BAHAMAS','BS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '048', 'BAHREIN','BH') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '050', 'BANGLADESH','BD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '052', 'BARBADE','BB') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '056', 'BELGIQUE','BE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '084', 'BELIZE','BZ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '204', 'BENIN','BJ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '064', 'BHOUTAN','BT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '112', 'BIELORUSSIE','BY') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '104', 'BIRMANIE','MM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '535', 'BONAIRE SAINT EUSTACHE ET SABA','BQ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '070', 'BOSNIE-HERZEGOVINE','BA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '072', 'BOTSWANA','BW') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '076', 'BRESIL','BR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '096', 'BRUNEI DARUSSALAM','BN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '100', 'BULGARIE','BG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '854', 'BURKINA FASO','BF') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '108', 'BURUNDI','BI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '116', 'CAMBODGE','KH') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '120', 'CAMEROUN','CM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '124', 'CANADA','CA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '132', 'CAP-VERT','CV') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '152', 'CHILI','CL') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '156', 'CHINE','CN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '196', 'CHYPRE','CY') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '170', 'COLOMBIE','CO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '174', 'COMORES','KM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '178', 'CONGO','CG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '180', 'CONGO (République Démocratique)','CD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '408', 'COREE (REP. POPULAIR. DEMOCRATI)','KP') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '410', 'COREE (REPUBLIQUE DE)','KR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '188', 'COSTA RICA','CR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '384', 'COTE D''IVOIRE','CI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '191', 'CROATIE','HR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '192', 'CUBA','CU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '531', 'CURACAO','CW') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '208', 'DANEMARK','DK') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '262', 'DJIBOUTI','DJ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '212', 'DOMINIQUE','DM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '818', 'EGYPTE','EG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '784', 'EMIRATS ARABES UNIS','AE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '218', 'EQUATEUR','EC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '724', 'ESPAGNE','ES') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '233', 'ESTONIE','EE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '598', 'ET INDT DE PAPOUASIE NLLE GUINEE','PG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '232', 'ETAT D''ERYTHREE','ER') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '068', 'ETAT PLURINATIONAL DE BOLIVIE','BO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '840', 'ETATS-UNIS','US') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '231', 'ETHIOPIE','ET') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '643', 'FEDERATION DE RUSSIE','RU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '242', 'FIDJI','FJ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '246', 'FINLANDE','FI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '266', 'GABON','GA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '270', 'GAMBIE','GM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '268', 'GEORGIE','GE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '239', 'GEORGIE DU SUD-ILES SANDWICH SUD','GS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '288', 'GHANA','GH') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '292', 'GIBRALTAR','GI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '300', 'GRECE','GR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '308', 'GRENADE','GD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '304', 'GROENLAND','GL') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '316', 'GUAM','GU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '320', 'GUATEMALA','GT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '831', 'GUERNESEY','GG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '324', 'GUINEE','GN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '226', 'GUINEE EQUATORIALE','GQ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '624', 'GUINEE-BISSAO','GW') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '328', 'GUYANA','GY') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '332', 'HAITI','HT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '340', 'HONDURAS','HN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '344', 'HONG-KONG','HK') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '348', 'HONGRIE','HU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '074', 'ILE BOUVET','BV') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '162', 'ILE CHRISTMAS','CX') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '833', 'ILE DE MAN','IM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '574', 'ILE NORFOLK','NF') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '136', 'ILES CAIMANES','KY') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '166', 'ILES COCOS (KEELING)','CC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '184', 'ILES COOK','CK') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '238', 'ILES FALKLAND (MALVINAS)','FK') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '234', 'ILES FEROE','FO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '334', 'ILES HEARD ET MC DONALD','HM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '580', 'ILES MARIANNES DU NORD','MP') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '581', 'ILES MINEURES ELOIGNEES DES E.U.','UM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '796', 'ILES TURKS ET CAIQUES','TC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '092', 'ILES VIERGES BRITANNIQUES','VG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '850', 'ILES VIERGES DES ETATS-UNIS','VI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '900', 'INCONNU','XA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '356', 'INDE','IN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '360', 'INDONESIE','ID') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '364', 'IRAN (REPUBLIQUE ISLAMIQUE D'')','IR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '368', 'IRAQ','IQ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '372', 'IRLANDE','IE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '352', 'ISLANDE','IS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '376', 'ISRAEL','IL') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '380', 'ITALIE','IT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '388', 'JAMAIQUE','JM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '392', 'JAPON','JP') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '832', 'JERSEY','JE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '400', 'JORDANIE','JO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '398', 'KAZAKHSTAN','KZ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '404', 'KENYA','KE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '417', 'KIRGHIZISTAN','KG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '296', 'KIRIBATI','KI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '957', 'KOSOVO','XK') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '414', 'KOWEIT','KW') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '418', 'LAOS (REP. DEMOC. POPULAIRE)','LA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '426', 'LESOTHO','LS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '428', 'LETTONIE','LV') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '422', 'LIBAN','LB') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '430', 'LIBERIA','LR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '434', 'LIBYE','LY') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '438', 'LIECHTENSTEIN','LI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '440', 'LITUANIE','LT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '442', 'LUXEMBOURG','LU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '446', 'MACAO','MO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '450', 'MADAGASCAR','MG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '458', 'MALAISIE','MY') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '454', 'MALAWI','MW') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '462', 'MALDIVES','MV') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '466', 'MALI','ML') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '470', 'MALTE','MT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '504', 'MAROC','MA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '584', 'MARSHALL (Iles)','MH') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '250', 'FRANCE','FR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '480', 'MAURICE','MU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '478', 'MAURITANIE','MR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '998', 'MER','XC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '484', 'MEXIQUE','MX') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '583', 'MICRONESIE (ETATS FEDERES DE)','FM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '498', 'MOLDAVIE','MD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '492', 'MONACO','MC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '496', 'MONGOLIE','MN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '499', 'MONTENEGRO','ME') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '500', 'MONTSERRAT','MS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '508', 'MOZAMBIQUE','MZ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '516', 'NAMIBIE','NA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '520', 'NAURU','NR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '524', 'NEPAL','NP') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '558', 'NICARAGUA','NI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '562', 'NIGER','NE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '566', 'NIGERIA','NG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '570', 'NIOUE','NU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '578', 'NORVEGE','NO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '554', 'NOUVELLE-ZELANDE','NZ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '086', 'OCEAN INDIEN (TERRIT.BRITANNIQ)','IO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '512', 'OMAN','OM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '800', 'OUGANDA','UG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '860', 'OUZBEKISTAN','UZ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '586', 'PAKISTAN','PK') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '585', 'PALAOS','PW') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '591', 'PANAMA','PA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '600', 'PARAGUAY','PY') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '528', 'PAYS-BAS','NL') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '604', 'PEROU','PE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '608', 'PHILIPPINES','PH') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '612', 'PITCAIRN','PN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '616', 'POLOGNE','PL') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '630', 'PORTO-RICO','PR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '620', 'PORTUGAL','PT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '634', 'QATAR','QA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '140', 'REPUBLIQUE CENTRAFRICAINE','CF') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '807', 'REPUBLIQUE DE MACEDOINE DU NORD','MK') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '214', 'REPUBLIQUE DOMINICAINE','DO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '891', 'REPUBLIQUE FEDER. DE YOUGOSLAVIE','XD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '706', 'REPUBLIQUE FEDERALE DE SOMALIE','SO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '203', 'REPUBLIQUE TCHEQUE','CZ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '642', 'ROUMANIE','RO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '826', 'ROYAUME-UNI','GB') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '646', 'RWANDA','RW') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '732', 'SAHARA OCCIDENTAL','EH') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '534', 'SAINT MARTIN PARTIE NEERLANDAISE','SX') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '659', 'SAINT-CHRISTOPHE-ET-NIEVES','KN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '674', 'SAINT-MARIN','SM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '670', 'SAINT-VINCENT-ET-LES-GRENADINES','VC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '654', 'SAINTE-HELENE','SH') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '662', 'SAINTE-LUCIE','LC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '090', 'SALOMON (Iles)','SB') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '222', 'SALVADOR','SV') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '882', 'SAMOA','WS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '016', 'SAMOA AMERICAINES','AS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '678', 'SAO TOME-ET-PRINCIPE','ST') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '686', 'SENEGAL','SN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '688', 'SERBIE','RS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '690', 'SEYCHELLES','SC') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '694', 'SIERRA LEONE','SL') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '702', 'SINGAPOUR','SG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '703', 'SLOVAQUIE','SK') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '705', 'SLOVENIE','SI') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '736', 'SOUDAN','SD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '728', 'SOUDAN DU SUD','SS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '144', 'SRI LANKA','LK') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '752', 'SUEDE','SE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '756', 'SUISSE','CH') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '740', 'SURINAME','SR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '744', 'SVALBARD ET ILE JAN MAYEN','SJ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '748', 'SWAZILAND','SZ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '760', 'SYRIE','SY') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '762', 'TADJIKISTAN','TJ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '158', 'TAIWAN','TW') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '834', 'TANZANIE','TZ') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '148', 'TCHAD','TD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '200', 'TCHECOSLOVAQUIE','CS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '275', 'TERRITOIRES PALESTINIENS','PS') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '764', 'THAILANDE','TH') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '626', 'TIMOR ORIENTAL','TL') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '768', 'TOGO','TG') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '772', 'TOKELAU','TK') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '776', 'TONGA','TO') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '780', 'TRINITE-ET-TOBAGO','TT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '795', 'TURKMENISTAN','TM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '792', 'TURQUIE','TR') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '798', 'TUVALU','TV') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '804', 'UKRAINE','UA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '810', 'URSS','SU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '858', 'URUGUAY','UY') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '548', 'VANUATU','VU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '336', 'VATICAN (SAINT-SIEGE)','VA') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '862', 'VENEZUELA','VE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '704', 'VIET NAM','VN') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '887', 'YEMEN','YE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '886', 'YEMEN DU NORD','YE') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '720', 'YEMEN DU SUD','YD') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '890', 'YOUGOSLAVIE','YU') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '894', 'ZAMBIE','ZM') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '716', 'ZIMBABWE','ZW') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '536', 'ZONE NEUTRE','NT') ON CONFLICT DO NOTHING;
INSERT INTO webapp.pays(id, code, libelle, mnemo)VALUES(nextval('webapp.pays_id_seq'), '788', 'TUNISIE','TN') ON CONFLICT DO NOTHING;