INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'à la demande des parties','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'absence avis JAP','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'absence enquête sociale rapide','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'au fond sur opposition','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'aux fins d’audience collégiale','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'aux fins d’audience en formation citoyenne','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'avant dire droit et sursis à statuer sur l’action publique','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'demande de délai pour préparer sa défense','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'en chambre du conseil','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'en continuation','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'en délibéré','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'en délibéré prorogé','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'en prorogation d’ajournement','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour absence d’interprète','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour absence de bulletin N°1','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour citation (témoin / partie civile)','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour comparution personnelle','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour compétence du tribunal correctionnel pour mineurs ','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour consignation de l’auteur','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour consignation de la partie civile','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour demande de désignation d’avocat','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour examen de la question préjudicielle','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour intervention forcée (CPAM, agent judiciaire du trésor)','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour investigations sur la personnalité ou la situation matérielle, familiale et sociale pour nouvelle citation','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour présence obligatoire suite à défaut d’extraction','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'pour recherche de l’opposant','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'sur ajournement','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'sur intérêts civils','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'vers la juridiction collégiale','', '1') ON CONFLICT DO NOTHING;
INSERT INTO webapp.renvoi_motif(id, code, libelle, mnemo, ordre)VALUES(nextval('webapp.renvoi_motif_id_seq'), '999', 'autre cas','', '1') ON CONFLICT DO NOTHING;